from importlib.metadata import version

from ._grouping import tiles_from_template
from .client import UnitlabClient
from .exceptions import (
    AmbiguousUploadCompletionError,
    AuthenticationError,
    NetworkError,
    NotFoundError,
    PermissionDeniedError,
    ProcessingTimeoutError,
    RequestTimeoutError,
    SubscriptionError,
    TimeoutError,
    UnitlabError,
    ValidationError,
)
from .ontology import (
    ChecklistAttribute,
    NumericAttribute,
    OntologyClassificationLevel,
    OntologyStructure,
    RadioAttribute,
    Shape,
    TextAttribute,
)
from .resources import (
    Asset,
    AttachedSource,
    BatchQueue,
    CloudStorage,
    Dataset,
    DatasetItem,
    DatasetVersion,
    DataUnit,
    EmbeddingSpace,
    Folder,
    GroupingResult,
    Ontology,
    Project,
    Release,
    UploadBatch,
    Workflow,
    WorkflowStage,
    WorkflowTask,
)
from .types import (
    AssetUploadResult,
    AttachPreview,
    AttachResult,
    CloudEntry,
    ProcessingStatus,
    UploadFailure,
)

__version__ = version("unitlab")

__all__ = [
    "AmbiguousUploadCompletionError",
    "Asset",
    "AssetUploadResult",
    "AttachPreview",
    "AttachResult",
    "AttachedSource",
    "AuthenticationError",
    "BatchQueue",
    "ChecklistAttribute",
    "CloudEntry",
    "CloudStorage",
    "DataUnit",
    "Dataset",
    "DatasetItem",
    "DatasetVersion",
    "EmbeddingSpace",
    "Folder",
    "GroupingResult",
    "NetworkError",
    "NotFoundError",
    "NumericAttribute",
    "Ontology",
    "OntologyClassificationLevel",
    "OntologyStructure",
    "PermissionDeniedError",
    "ProcessingStatus",
    "ProcessingTimeoutError",
    "Project",
    "RadioAttribute",
    "Release",
    "RequestTimeoutError",
    "Shape",
    "SubscriptionError",
    "TextAttribute",
    "TimeoutError",
    "UnitlabClient",
    "UnitlabError",
    "UploadBatch",
    "UploadFailure",
    "ValidationError",
    "Workflow",
    "WorkflowStage",
    "WorkflowTask",
    "__version__",
    "tiles_from_template",
]
